// This file is auto-generated by dtscommands.
// Do not edit this file manually.
import { Guild } from 'discord.js'
import { Event } from 'dtscommands'
import client from '../../../index.js'
import chalk from 'chalk'

export class GuildJoinEvent extends Event<'guildCreate'> {
  constructor () {
    super({
      name: 'guildCreate',
      nick: 'guildJoin'
    })
  }

  async run (guild: Guild) {
    // await prisma.guild.create({
    //   data: {
    //     guildId: guild.id
    //   }
    // })
  }
}

export class ReadyEvent extends Event<'ready'> {
  constructor () {
    super({
      name: 'ready',
      once: true
    })
  }

  run () {
    console.info(`Client logged in as "${client.user?.tag}"`, chalk.bold('cli'))
    // bot.application?.commands.set(bot.commands.array)
  }
}
